// atomic/pages/Register/index.vue
<template>
  <nuc-home-link />
  <div class="auth-card-container">
    <ad-card class="register-card">
      <template #header>
        <div class="auth-card-header-container">
          <div class="auth-card-header">
            <ad-heading :tag="1" :text="t('auth-register-heading')" />

            <ad-paragraph :text="t('auth-register-has-account')">
              <ad-anchor
                :href="`/${lang}/login`"
                :label="t('auth-register-login')"
              />
            </ad-paragraph>
          </div>
        </div>
      </template>
      <template #content>
        <form @submit.prevent="submitAndGo(registerFields)">
          <ad-float-label v-for="(field, index) in registerInputs" :key="index">
            <ad-input-text
              v-if="field.type !== 'password'"
              :id="field.id"
              v-model="registerFields[field.model]"
              ad-type="main"
              :type="field.type"
              class="auth-input-text"
              :autofocus="field.autofocus"
            />

            <ad-password
              v-else
              :id="field.id"
              v-model="registerFields[field.model]"
              ad-type="main"
              class="auth-input-text"
              :autofocus="field.autofocus"
              :passwords-match="
                passwordsMatch(
                  registerFields['password'],
                  registerFields['password_confirmation']
                ) && field.model === 'password_confirmation'
              "
              :empty-password="
                isEmpty(registerFields['password']) &&
                field.model === 'password_confirmation'
              "
              :empty-confirm-password="
                isEmpty(registerFields['password_confirmation']) &&
                field.model === 'password_confirmation'
              "
            />

            <ad-label :for="field.id" :label="t(field.label)" />
          </ad-float-label>

          <ad-button :label="t('auth-register-submit')" type="submit" />
        </form>
      </template>
    </ad-card>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import { isEmpty, passwordsMatch, useAuthForm } from 'nucleify'

const route = useRoute()
const { t } = useI18n()
const lang = computed(() => (route.params.lang as string) || 'en')

const { submitAndGo, registerFields, registerInputs } = useAuthForm()

onMounted((): void => {
  passwordsMatch(
    registerFields.value.password,
    registerFields.value.password_confirmation
  )
})
</script>

// atomic/pages/register.tsx
'use client'

import { useParams } from 'next/navigation'
import type { ChangeEvent, FormEvent, JSX } from 'react'

import {
  AdButton,
  AdCard,
  AdFloatLabel,
  AdHeading,
  AdInputText,
  AdLabel,
  AdParagraph,
  AdPassword,
  isEmpty,
  passwordsMatch,
  type RegisterFieldKey,
  t,
  useAuthForm,
} from 'nucleify'

import './_index.scss'

export function NucRegisterPage(): JSX.Element {
  const params = useParams<{ lang?: string }>()
  const lang = params?.lang ?? 'en'
  const { submitAndGo, registerFields, setRegisterFields, registerInputs } =
    useAuthForm('next', lang)

  function handleSubmit(event: FormEvent<HTMLFormElement>): void {
    event.preventDefault()
    void submitAndGo(registerFields)
  }

  function updateField(model: RegisterFieldKey, value: string): void {
    setRegisterFields((prev) => ({
      ...prev,
      [model]: value,
    }))
  }

  return (
    <div className="auth-card-container">
      <AdCard
        className="register-card"
        header={
          <div className="auth-card-header-container">
            <div className="auth-card-header">
              <AdHeading tag={1} text={t('auth-register-heading')} />
              <AdParagraph text={t('auth-register-has-account')}>
                <a href={`/${lang}/login`}>{t('auth-register-login')}</a>
              </AdParagraph>
            </div>
          </div>
        }
      >
        <form onSubmit={handleSubmit}>
          {registerInputs.map((field) => {
            const model = field.model as RegisterFieldKey
            const isPasswordField = field.type === 'password'

            return (
              <AdFloatLabel key={field.id}>
                {isPasswordField ? (
                  <AdPassword
                    id={field.id}
                    nuiType="main"
                    className="auth-input-text"
                    autoFocus={field.autofocus}
                    value={registerFields[model]}
                    onChange={(event: ChangeEvent<HTMLInputElement>) => {
                      updateField(model, event.target.value)
                    }}
                    passwordsMatch={
                      model === 'password_confirmation' &&
                      passwordsMatch(
                        registerFields.password,
                        registerFields.password_confirmation
                      )
                    }
                    emptyPassword={
                      model === 'password_confirmation' &&
                      isEmpty(registerFields.password)
                    }
                  />
                ) : (
                  <AdInputText
                    id={field.id}
                    nuiType="main"
                    type={field.type}
                    className="auth-input-text"
                    autoFocus={field.autofocus}
                    value={registerFields[model]}
                    onChange={(event: ChangeEvent<HTMLInputElement>) => {
                      updateField(model, event.target.value)
                    }}
                  />
                )}
                <AdLabel forInput={field.id} label={t(field.label)} />
              </AdFloatLabel>
            )
          })}

          <AdButton label={t('auth-register-submit')} type="submit" />
        </form>
      </AdCard>
    </div>
  )
}
