// atomic/templates/TestLoginButtons/index.vue
<template>
  <div class="test-login-buttons-container">
    <ad-button icon="prime:crown" rounded @click="loginAndGo('admin')" />
    <ad-button
      icon="prime:user"
      severity="secondary"
      rounded
      @click="loginAndGo('user')"
    />
  </div>
</template>

<script setup lang="ts">
import { useRoute, useRouter } from '#app'

import { testLogin } from 'nucleify'

const route = useRoute()
const router = useRouter()
const lang = (route.params.lang as string) || 'en'

async function loginAndGo(role: string) {
  await testLogin(role)
  router.push(`/${lang}/entities`)
}
</script>

<style lang="scss">
@import 'index';
</style>

// atomic/templates/TestLoginButtons/index.tsx
'use client'

import { useParams } from 'next/navigation'
import type { JSX } from 'react'

import { AdButton, navigateToUrl, testLogin } from 'nucleify'

import './_index.scss'

export function NucTestLoginButtons(): JSX.Element {
  const params = useParams<{ lang?: string }>()
  const lang = params?.lang ?? 'en'

  async function loginAndGo(role: 'admin' | 'user'): Promise<void> {
    await testLogin(role)
    navigateToUrl(`/${lang}/entities`)
  }

  return (
    <div className="test-login-buttons-container">
      <AdButton
        icon="prime:crown"
        rounded
        type="button"
        onClick={() => void loginAndGo('admin')}
      />
      <AdButton
        icon="prime:user"
        severity="secondary"
        rounded
        type="button"
        onClick={() => void loginAndGo('user')}
      />
    </div>
  )
}
